config {
  type: "view",
  schema: "silver", 
  name: "${dataform.vars.master_tracker_export_view}",
  description: "View MASTER TRACKER EXPORT",
  tags: ["silver", "ltm", "master_tracker_export"]
}

SELECT j.job_number                                                                         AS `Job Number`  
     , TRIM(jt.name)                                                                        AS `Job Type` 
     , TRIM(bu.name)                                                                        AS `Business Unit`
     , p.number                                                                             AS `Project`
     , CASE WHEN j.recall_for_id IS NULL THEN FALSE ELSE TRUE END                           AS `Recall`
     , TRIM(t.name)                                                                         AS `Lead Generated By`
     , j.job_generated_lead_source_job_id                                                   AS `Lead Generated From`
     , (
        SELECT SUM(sub_total)                                                               AS `sub_total`
          FROM `${dataform.projectId}.${dataform.vars.raw_dataset}.invoice`                 invoice
         WHERE project_id                                                                   = j.project_id
       )                                                                                    AS `Sales from Leads Created`
     , i.total                                                                              AS `Total`
     , FORMAT_DATE("%m/%d/%Y",${dataform.vars.bronze_dataset}.convert_utc_localtz(j.completed_on,'MONARCH')) AS `Completion Date`
     , j.customer_id                                                                        AS `Customer Id`
     , TRIM(c.name)                                                                         AS `Customer Name` 
     , TRIM(ts.name)                                                                        AS `Sold By` 
     , ARRAY_TO_STRING(IFNULL(ti.assigned_technicians, []), ', ')                           AS `Assigned Technicians`
     , TRIM(ti.primary_technician)                                                          AS `Primary Technician`
     , es.subtotal                                                                          AS `Estimate Sales Subtotal`
     , TRIM(ca.name)                                                                        AS `Job Campaign`
     , ROUND(i.sold_hours,2)                                                                AS `Sould Hours`
  FROM `${dataform.projectId}.${dataform.vars.raw_dataset}.job`                             j 
  LEFT JOIN `${dataform.projectId}.${dataform.vars.bronze_dataset}.job-types`               jt
    ON jt.id                                                                                = j.job_type_id
  LEFT JOIN `${dataform.projectId}.${dataform.vars.raw_dataset}.business_unit`              bu
    ON bu.id                                                                                = j.business_unit_id
  LEFT JOIN `${dataform.projectId}.${dataform.vars.raw_dataset}.project`                    p
    ON p.id                                                                                 = j.project_id
  LEFT JOIN `${dataform.projectId}.${dataform.vars.raw_dataset}.employee`                   e
    ON e.id                                                                                 = j.job_generated_lead_source_employee_id
  LEFT JOIN `${dataform.projectId}.${dataform.vars.bronze_dataset}.technicians`             t
    ON t.id                                                                                 = j.job_generated_lead_source_employee_id
  LEFT JOIN 
       (
        SELECT i1.job_id                                                                    AS job_id
             , AVG(i1.sub_total)                                                            AS total
             , SUM(i2.sold_hours)                                                           AS sold_hours  
          FROM `${dataform.projectId}.${dataform.vars.raw_dataset}.invoice`                 i1
          LEFT JOIN `${dataform.projectId}.${dataform.vars.raw_dataset}.invoice_item`       i2
            ON i2.invoice_id                                                                = i1.id
         GROUP BY                                                                           i1.job_id
       )                                                                                    i
    ON i.job_id                                                                             = j.id   
  LEFT JOIN `${dataform.projectId}.${dataform.vars.raw_dataset}.customer`                   c
    ON c.id                                                                                 = j.customer_id
  LEFT JOIN 
       (
        SELECT js.job_id                                                                    AS job_id
             , ARRAY_AGG(DISTINCT IFNULL(t.name, ''))                                       AS assigned_technicians
             , ARRAY_AGG(IFNULL(t.name, '') ORDER BY js.split DESC LIMIT 1)[SAFE_OFFSET(0)] AS primary_technician
          FROM `${dataform.projectId}.${dataform.vars.raw_dataset}.job_split`               js
          LEFT JOIN `${dataform.projectId}.${dataform.vars.bronze_dataset}.technicians`     t 
            ON js.technician_id                                                             = t.id
         GROUP BY                                                                           js.job_id
       )                                                                                    ti 
    ON ti.job_id                                                                            = j.id
  LEFT JOIN `${dataform.projectId}.${dataform.vars.bronze_dataset}.technicians`             ts
    ON ts.id                                                                                = j.sold_by_id    
  LEFT JOIN 
       (
        SELECT job_id                                                                       AS job_id
             , SUM(subtotal)                                                                AS subtotal
          FROM `${dataform.projectId}.${dataform.vars.raw_dataset}.estimate`                estimate
         WHERE sold_on                                                                      IS NOT NULL 
           AND active                                                                       IS TRUE
         GROUP BY                                                                           job_id 
       )                                                                                    es 
    ON es.job_id                                                                            = j.id      
  LEFT JOIN `${dataform.projectId}.${dataform.vars.bronze_dataset}.campaigns`               ca
    ON ca.id                                                                                = j.campaign_id
   AND j.job_status                                                                         = 'Completed'
ORDER BY j.completed_on